import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import SideBar from "./components/side-bar/side-bar";
import NavBar from "./components/navigation-bar/nav-bar";

const nunito = Nunito_Sans({
  subsets: ["latin"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-screen nunito-sans grid grid-cols-[240px_1fr] ${nunito.className}`}>
        <div></div>
        <SideBar />
        <div className="flex flex-col">
          <NavBar />
          <div className="bg-bgdashboard w-full h-full p-[30px]">{children}</div>
        </div>
      </body>
    </html>
  );
}
