import type { Metadata } from "next";
import "./globals.css";
import NavBar from "../components/navigation-bar/nav-bar";
import SideBar from "../components/side-bar/side-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen nunito-sans grid grid-cols-[240px_1fr]">
        <div></div>
        <SideBar whoIsActive="products" />
        <div className="flex flex-col">
          <NavBar />
          <div className="bg-bgdashboard w-full h-full p-[30px]">{children}</div>
        </div>
      </body>
    </html>
  );
}
